image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.theia/init_tasks.sh    
vscode:
  extensions:
    - ms-python.python@2019.8.30787:TnGEOx35GXMhyKLjDGz9Aw==
    - formulahendry.auto-close-tag@0.5.9:JZIefALANqOfhSK1TU4+Fw==
    - mkaufman.HTMLHint@0.10.0:xevX4CvYOkKd8xjvtJQiGQ==
    - eventyret.bootstrap-4-cdn-snippet@1.9.0:I8wcXFcKWQIROg7J0SLLqg==
    - esbenp.prettier-vscode@5.7.1:4Zx39KyQMoIz7x94PSmDmQ==
    - kevinglasson.cornflakes-linter@0.5.1:KAaMshgHOKan8eojXQ53OQ==


    - dracula-theme.theme-dracula@2.22.3:c2qxutk2xT/UW8L9+9bW2g==
    - mike-flanigan.daobeam@1.3.12:r/wa3pJ/dFYd+gcQxnC4Zw==
    - enkia.tokyo-night@0.6.7:lhDqELvXYMdMmyvU/DrG/Q==
    - teabyii.ayu@0.20.1:fJGIE2FGGQwXsOZ/boL0NA==
    - vladeeg.vscode-theme-vdark@1.1.0:IbJj2Pm0zXoREGuG7LGa2g==